# docker build -f Dockerfile.test -t pgautoupgrade:17-fix .

FROM pgautoupgrade/pgautoupgrade:17.7-debian

COPY postgres-docker-entrypoint.fix.sh /usr/local/bin/postgres-docker-entrypoint.sh

# Just to be explicit
ENV TEST_BREAKPOINT=1
